name: Android CI

on:
  push:
    branches:
      - develop
      - main
    paths: [ 'Android/**' ]
  pull_request:
    branches:
      - develop
      - main
    paths: 'Android/**'

defaults:
  run:
    working-directory: Android

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build assemble release apk
        run: ./gradlew assembleRelease
