name: iOS CI

on:
  push:
    branches:
      - develop
      - main
    paths: [ 'iOS/**' ]
  pull_request:
    branches:
      - develop
      - main
    paths: 'iOS/**'
    
defaults:
  run:
    working-directory: iOS

jobs:
  build:  

    runs-on: macos-latest 

    steps:
    - uses: actions/checkout@v3 
    - name: Build Xcode  
      run: |  
        xcodebuild clean test -project banchango.xcodeproj \
        -scheme banchango \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
