name: iOS CI

on:
  push:
    branches: [ develop ] 
  pull_request:
    branches: [ develop ]

jobs:
  build:  

    runs-on: macos-latest 

    steps:
    - uses: actions/checkout@v4  
    - name: Build Xcode  
      run: |  
        xcodebuild clean test -project banchango.xcodeproj \
        -scheme banchango \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
